### ISSUE TITLE
Pulling bundles is jacked (sometimes)

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#177]
@decleaver and I observed a behavior where sometimes pulling a bundle results in strange errors about missing layers. We think this is because `pull`, unlike the other bundle operations, occurs in the cache directory as opposed to a tmp dir. 

```[tasklist]
### Tasks
- [x] Decouple the zarf-cache entirely from UDS CLI
- [x] Ensure during testing that we deploy the pulled bundle
- [x] Check for places where we null check "Annotations" and it more robust (ie. check the content of the annotations, not just their existence)
- [x] Refactor pull
```
