### ISSUE TITLE
Refactor OCI

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#350]
```[tasklist]
### Tasks
- [x] Address `todo`s in the OCI code
- [x] Go through the OCI code with @decleaver and think through the current OCI code structure
- [x] ~Change bundle root manifest media types to image manifest intead of Zarf blob (for the ones that point to Zarf manifests)~
- [x] Ensure SHAs are correct
- [x] Refactor the way we verify which layers need to be pulled (potentially modify the Zarf image manifest; don't forget to re-hash)
```

**Comment by UncleGedd** [comment]
Merged in initial refactor PR, revisit in a week or so when the big OCI refactor is merged in

**Comment by UncleGedd** [comment]
@Racer159 is contributing to this issue in https://github.com/defenseunicorns/uds-cli/pull/581

**Comment by UncleGedd** [comment]
Related issue and PR:
- https://github.com/defenseunicorns/uds-cli/pull/599
- https://github.com/defenseunicorns/uds-cli/issues/608

**Comment by UncleGedd** [comment]
We've refactored a ton of OCI code in https://github.com/defenseunicorns/uds-cli/pull/622, closing this ticket in favor of more specific tech debt issues
