### ISSUE TITLE
Refine dev deploy

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#550]
```[tasklist]
### Tasks
- [x] ensure SBOMs are skipped by default
- [x] add --packages
- [x] mark as beta
- [ ] https://github.com/defenseunicorns/uds-cli/issues/537
- [x] add --flavor flag
- [ ] https://github.com/defenseunicorns/uds-cli/issues/628
```

**Comment by decleaver** [comment]
blocked while #537 gets worked

**Comment by andrewg-xyz** [comment]
All tasks are complete? closing.
