### ISSUE TITLE
Improve dev docs and use Maru

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#583]
## Description

Refactor dev docs to make it easier for new contributors to know where to start and use Maru tasks (ie. `uds run`) to dogfood the runner capability

```[tasklist]
### Tasks
- [x] Add sections to `CONTRIBUTING.md` about test strategy and expectations
- [x] Refactor Makefile to use Maru tasks where applicable
- [x] Refactor Github workflows to use Maru tasks where applicable
- [x] Explore how to do `go install github.com/defenseunicorns/uds-cli@v0.10.4`
```

**Comment by UncleGedd** [comment]
I researched `go install` but it looks like it's untenable because of all of our Go build args/vars

**Comment by UncleGedd** [comment]
Closed with https://github.com/defenseunicorns/uds-cli/pull/602
