### ISSUE TITLE
Policy Logs - MVP

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/uds-cli#663]
## User Story ##

As [Jaqueline ](https://userbit.com/external/88iAMwjH1tCrv1ZerWpt/persona/BcG0ArJ5yO8sLegQkOhk)(an SRE), I would like to know when the policy engine does (blocks, mutatues, etc) something and it's status without having to have pepr or node installed on my machine. This needs to be a long-lived record or log to be used for investigating issues.

### Scenario 1: View aggregated log output in the UI ###
Given Jaqueline is logged into the Kubernetes Tool
When she navigates to the "Monitor" section in the left navigation
And selects the "Pepr" option
Then she should see an aggregated log output that combines policy enforcement and operator actions
This output should be a stream of the terminal log output served in the web UI
And each log record should include the timestamp, resource name, action type, and message

### Scenario 2: Access aggregated log output using the CLI ###
Given Jaqueline has the Kubernetes Tool CLI installed
When she runs the command "UDS monitor Pepr"
Then she should see an aggregated log output that combines policy enforcement and operator actions
And each log record should include the timestamp, resource name, action type, and message

### Scenario 3: Access aggregated log output using the CLI with arguments and flags ###
Given Jaqueline has the Kubernetes Tool CLI installed
When she runs the command "UDS monitor pepr -n <namespace>"
Then she should see an aggregated log output that combines policy enforcement and operator actions for the specified namespace
And each log record should include the timestamp, resource name, action type, and message
When she runs the command "UDS monitor pepr --namespace <namespace>"
Then she should see an aggregated log output that combines policy enforcement and operator actions for the specified namespace
And each log record should include the timestamp, resource name, action type, and message
When she runs the command "UDS monitor pepr -n <namespace> --follow"
Then she should see an aggregated log output that combines policy enforcement and operator actions for the specified namespace
And the log output should continuously update with new log records in real-time
And each log record should include the timestamp, resource name, action type, and message
This scenario expands on Scenario 2 by including the use of command arguments and flags in the CLI:

-n <namespace> or --namespace <namespace>: Specifies the namespace to filter the log output. Only log records related to the specified namespace will be displayed.
--follow: Enables real-time streaming of the log output. The log will continuously update with new log records as they occur.

```[tasklist]
### Task List
- [x] Design prototype in figma for Pepr Log page
- [x] UI  Build out policy logs page in web UI using Figma Design Frame: [Policy enforcement basic/stream of logs](https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Engine-(UI%2FCLI)?node-id=2571-38156&m=dev)
- [ ] Build out API for serving out per policy logs (timestamp, policy type, policy name, additional details, repeated)
- [x] Build out CLI log view `UDS monitor policies`
- [x] UI -  Stream logs data into web UI (scroll bar in log window, logs in same order as terminal)
- [ ] Write tests
```

## Figma Files and designs ##

[Figma File for designs](https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Engine-(UI%2FCLI)?m=dev&node-id=2571-38156&t=1fR19vl413HaubvG-1)

![Image](https://github.com/defenseunicorns/uds-cli/assets/92826525/2c50006d-07a0-4676-b0df-15fa438dd23b)

**Comment by Madeline-UX** [comment]
@cole has done previous working on Zarf UI for streaming log output in the UI without breaking formatting.

**Comment by Madeline-UX** [comment]
## Usability Testing Notes:
_areas to focus observations/testing on_
- Color of the resource name (color or bright white)
- Color of denied text (color or white)
- Can the user find policy exemptions?
- Would users benefit from linking to policy exemptions?
- How fast can a user find the log/info they are looking for?
- Do users have to go outside of the CLI/UI to get more info to complete their task?

**Comment by Madeline-UX** [comment]
Similar tool - for reference. https://github.com/stakater/Forecastle

**Comment by Madeline-UX** [comment]
CLI command structure for `UDS monitor Pepr`

![Image](https://github.com/defenseunicorns/uds-cli/assets/92826525/8065c8bc-bd3d-496b-b16e-bcf1369830b5)

**Comment by UncleGedd** [comment]
Waiting on engine things from @jeff-mccoy

**Comment by adam-defenseunicorns** [comment]
Closing See: https://github.com/defenseunicorns/uds-runtime
