### ISSUE TITLE
Distinguish between stdout and stderr

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#722]
### Describe what should be investigated or refactored

Today UDS CLI outputs virtually all output to `stderr`. Instead of using `stderr` exclusively, let's decide which output should go to `stdout` and which should go to `stderr`. As a rule of thumb, output that can be acted upon (such as `uds monitor`, `uds inspect`, etc) should go to `stdout` so downstream users don't have to do redirects.

```[tasklist]
### Tasks
- [ ] Write an ADR to reflect the decision
- [ ] Update contributing docs
- [ ] Update code to reflect the distinction
```
