### ISSUE TITLE
Continue overrides refactor

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-cli#760]
```[tasklist]
### Tasks
- [ ] Determine if we need an e2e test for handling a single Zarf pkg component with multiple charts
- [ ] Look into creating a type for Zarf vars, currently they are `map[string]string`
- [ ] Look into using `overrideData` for `processOverrideValues`
- [ ] Move some unit tests from `deploy_test.go` into `overrides_test.go` for testing code in `overrides.go`
```
